/**
 * Migration runner.
 *
 * Applies the SQL files in `./migrations/` (generated by
 * `drizzle-kit generate`) to the database. Idempotent: each
 * migration records itself in Drizzle's `__drizzle_migrations`
 * table and is skipped on subsequent runs.
 *
 * Two ways to invoke:
 *
 *   1. **Programmatic:** `runMigrations(db)` from any caller
 *      that already owns a Drizzle connection. The `DbStore`
 *      constructor uses this path so production startup and
 *      test setup share a single migration entry point.
 *   2. **Standalone CLI:** running this file directly via
 *      `pnpm db:migrate` (which executes `tsx src/db/migrate.ts`)
 *      applies migrations against `process.env.DATABASE_URL`
 *      and prints a one-line confirmation. Useful for ops
 *      workflows that want to migrate without booting the full
 *      Express server.
 *
 * The migration folder is resolved relative to the *current
 * module's URL* (not the process CWD) so the runner works
 * whether it's invoked via `tsx src/index.ts` (dev) or
 * `node dist/db/migrate.js` (prod) — both end up pointing at
 * the same compiled files.
 *
 * The CLI path is gated by a `main`-style guard at the bottom
 * of this file: it only fires when the module is invoked as
 * the process entry, never when it's imported as a side
 * dependency. This keeps the `import { runMigrations }` path
 * side-effect-free for `index.ts` and tests.
 */
import { pathToFileURL } from 'url';
import { fileURLToPath } from 'url';
import { dirname, resolve } from 'path';
import { migrate } from 'drizzle-orm/better-sqlite3/migrator';
import { getDb } from './client.js';
import type { Db } from './client.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

/** Absolute path to the migrations folder. Resolved once at
 *  module load so all callers see the same value. */
const MIGRATIONS_FOLDER = resolve(__dirname, 'migrations');

/**
 * Apply any pending migrations to the given Drizzle DB.
 *
 * Drizzle's `migrate()` is synchronous (matching
 * `better-sqlite3`'s sync model), so no `await` is needed.
 */
export function runMigrations(db: Db): void {
  migrate(db, { migrationsFolder: MIGRATIONS_FOLDER });
}

/** Exposed for tests / diagnostics. */
export const migrationsFolder = MIGRATIONS_FOLDER;

/**
 * Standalone-CLI entry point. Fires only when this file is
 * the process entry (e.g. `tsx src/db/migrate.ts`):
 *
 *   - `process.argv[1]` is the path Node / tsx actually
 *     executed. We compare it against this module's URL via
 *     `pathToFileURL` so the comparison is portable across
 *     Windows / POSIX path separators.
 *   - When this module is merely *imported* (from `index.ts`
 *     or vitest), `process.argv[1]` points elsewhere and the
 *     guard is silent.
 *
 * The comparison must use `import.meta.url` (not `__filename`)
 * because `import.meta.url` survives tsx's source-map rewriting
 * unchanged, whereas `__filename` does not.
 */
const entryUrl = process.argv[1] ? pathToFileURL(process.argv[1]).href : '';
if (entryUrl !== '' && import.meta.url === entryUrl) {
  runMigrations(getDb());
  console.log('Migrations applied.');
}